project:
  type: website

website:
  title: "Alex Gallin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Vignettes
        menu:
          - href: project1.qmd
            text: Project 1
          - href: project2.qmd
            text: Project 2
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



