project:
  type: website

website:
  title: "Alex Gallin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Vignettes
        menu:
          - href: project1.qmd
            text: Project 1
          - href: project2.qmd
            text: Project 2
  page-footer: This is a Quarto website.  To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
  favicon: favicon.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



